---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-app
  namespace: default
  labels:
    app: k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: "devopshint/nodejsapp-1.0:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app
  namespace: default
spec:
  selector:
    app: k8s-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
